version: '3.8'

services:
  db:
    image: postgres:15
    container_name: ecom-db
    restart: always
    env_file: .env
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "5432:5432"
    networks:
      - ecom-network
      
  backend:
    build: 
      context: ./ecom
      dockerfile: Dockerfile
    container_name: ecom-backend
    ports:
      - "8080:8080"
    env_file: .env
    volumes:
      - uploads-volume:/app/uploads  # Montando volume persistente para uploads
    networks:
      - ecom-network
    depends_on:
      - db

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: ecom-frontend
    ports:
      - "3000:3000"
    env_file: .env
    depends_on:
      - backend
    networks:
      - ecom-network

volumes:
  uploads-volume:  # Criando volume para persistir uploads

networks:
  ecom-network:
    driver: bridge
